name: Maps Digest Sender

on:
  workflow_dispatch: # Это разрешает ручной запуск
  schedule:
    # Четверг в 10:00 по Москве
    - cron: '0 7 * * 4'
    # Суббота в 14:00 по Москве
    - cron: '0 11 * * 6'

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Получение кода
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Установка библиотек
        run: pip install feedparser requests

      # Этот блок сработает ТОЛЬКО при ручном нажатии кнопки (для теста)
      - name: ТЕСТ: Запуск дайджеста РФ
        if: github.event_name == 'workflow_dispatch'
        run: python bot.py RU

      # Эти блоки сработают ТОЛЬКО по расписанию
      - name: Запуск дайджеста РФ (По расписанию Чт)
        if: github.event.schedule == '0 7 * * 4'
        run: python bot.py RU

      - name: Запуск дайджеста МИР (По расписанию Сб)
        if: github.event.schedule == '0 11 * * 6'
        run: python bot.py WORLD
