name: Maps Bot
on:
  workflow_dispatch:
  schedule:
    # Пон в 12:50 МСК (что равно 09:50 UTC)
    - cron: '50 9 * * 1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip install feedparser requests
    
    # 1. Сначала отправляем шапку с датами
    - name: Send Header
      if: github.event.schedule == '50 9 * * 1' || github.event_name == 'workflow_dispatch'
      run: python bot.py HEADER
      
    # 2. Потом Маркетинг
    - name: Marketing
      if: github.event.schedule == '50 9 * * 1' || github.event_name == 'workflow_dispatch'
      run: python bot.py MARKETING
      
    # 3. Потом РФ
    - name: Russia
      if: github.event.schedule == '50 9 * * 1' || github.event_name == 'workflow_dispatch'
      run: python bot.py RU
      
    # 4. В конце Мир
    - name: World
      if: github.event.schedule == '50 9 * * 1' || github.event_name == 'workflow_dispatch'
      run: python bot.py WORLD
