name: Maps Bot
on:
  workflow_dispatch:
  schedule:
    # 16:20 МСК = 13:20 UTC
    - cron: '20 5 * * 2'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip install feedparser requests
    
    - name: Send Header
      run: python bot.py HEADER
      
    - name: Marketing
      run: python bot.py MARKETING
      
    - name: Russia
      run: python bot.py RU
      
    - name: World
      run: python bot.py WORLD
