name: Main Scoring Bot
on:
  workflow_dispatch:
  schedule:
    # Запускается в Пон в 12:30 МСК (что равно 09:30 UTC)
    - cron: '30 9 * * 1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip install feedparser requests
    
    - name: Send Header
      if: github.event.schedule == '30 9 * * 1' || github.event_name == 'workflow_dispatch'
      run: python main.py HEADER
      
    - name: Marketing
      if: github.event.schedule == '30 9 * * 1' || github.event_name == 'workflow_dispatch'
      run: python main.py MARKETING
      
    - name: Russia
      if: github.event.schedule == '30 9 * * 1' || github.event_name == 'workflow_dispatch'
      run: python main.py RU
      
    - name: World
      if: github.event.schedule == '30 9 * * 1' || github.event_name == 'workflow_dispatch'
      run: python main.py WORLD
