name: Main Scoring Bot
on:
  workflow_dispatch:
  schedule:
    # Запускается в Пон в 10:15 МСК (на 15 минут позже основного, чтобы не было конфликта в канале)
    - cron: '15 7 * * 1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip install feedparser requests
    
    - name: Send Header
      if: github.event.schedule == '5 7 * * 4' || github.event_name == 'workflow_dispatch'
      run: python main.py HEADER
      
    - name: Marketing
      if: github.event.schedule == '5 7 * * 4' || github.event_name == 'workflow_dispatch'
      run: python main.py MARKETING
      
    - name: Russia
      if: github.event.schedule == '5 7 * * 4' || github.event_name == 'workflow_dispatch'
      run: python main.py RU
      
    - name: World
      if: github.event.schedule == '5 7 * * 4' || github.event_name == 'workflow_dispatch'
      run: python main.py WORLD
