name: Main Scoring Bot
on:
  workflow_dispatch:
  schedule:
    # 16:00 МСК = 13:00 UTC
    - cron: '0 13 * * 1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip install feedparser requests
    
    - name: Send Header
      run: python main.py HEADER
      
    - name: Marketing
      run: python main.py MARKETING
      
    - name: Russia
      run: python main.py RU
      
    - name: World
      run: python main.py WORLD
